#!/usr/bin/env bash
# Script that installs Nginx server and configures redirect
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Jukunye permanent;/" /etc/nginx/sites-available/default
service nginx restart
