#!/usr/bin/env bash
# Script that installs Nginx server and configures redirect
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "s/server_name _;/&\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Jukunye permanent;\n\n\terror_page 404 \/404.html;\n\tlocation \/404 {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
service nginx restart
