#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.

current_date=$(date +'%d-%m-%Y')
mysqldump --user=root --password="$1" --all-databases > backup.sql
tar -czvf "${current_date}.tar.gz" backup.sql
