#!/usr/bin/env bash
#This script displays numbers from 1 t0 100.

i=1
while [ $i -le 100 ]; do
	if ((i % 3 == 0 && i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
