#!/usr/bin/env bash
# This script is displaying "Best School" 10 times except for 4 and 8.

num=1
while [ $num -le 10 ]; do

	if [ $num -eq 4 ]; then
		echo "bad luck"
	elif [ $num -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	
	((num++))
done
