#!/usr/bin/env bash
# This script is displays numbers from 1 to 20.

num=1
while [ $num -le 20 ]; do
	echo "$num"

	if ((num == 4)); then
		echo "bad luck from China"
	fi

	if ((num == 9)); then
		echo "bad luck from Japan"
	fi

	if ((num == 17)); then
		echo "bad luck from Italy"
	fi
	
	((num++))
done
